### ISSUE TITLE
Doesn't work with rspec-rails 3.0.2 (undefined method configure)

### ISSUE THREAD

**Issue by mehulkar** [guard/guard-zeus#29]
I'm not sure what the problem is, but with rails 4.2.3 and rspec-rails 3.0.2, this does not work out of box. I always forget why and how to fix. These are the steps I'm taking:

1. `gem 'guard-zeus'` # in Gemfile
1. `guard init zeus`
1. `guard`

```
 `<top (required)>': undefined method `configure' for RSpec:Module (NoMethodError)
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mehulkar/dev/backend/spec/rails_helper.rb:3:in `<top (required)>'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus/rails.rb:196:in `test_helper'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:200:in `run_action'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:74:in `block (2 levels) in boot_steps'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:7:in `features_loaded_by'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:73:in `block in boot_steps'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:56:in `catch'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:56:in `boot_steps'
  from /Users/mehulkar/.rvm/gems/ruby-2.1.1@nimble/gems/zeus-0.15.4/lib/zeus.rb:48:in `go'
```

**Comment by qnm** [comment]
@mehulkar Can you paste in the output of just running `zeus start` please?

**Comment by e2** [comment]
`bundle exec guard` ?

(Bundler requires files automatically from the Gemfile)

**Comment by qnm** [comment]
@e2 Yes - it looks like a zeus-related issue. Using bundler is a reasonable shortcut to diagnosis!

**Comment by e2** [comment]
@qnm - I'll probably have to rework dependency handling in Guard at some point (it's a nightmare), and Zeus seems to be the most complex case (different environment variables, forking, etc.), so I'm always interested in these kinds of problems. Feel free to cc me for any issue and/or suggestions about this.

**Comment by mehulkar** [comment]
```bash
➜  test_zeus git:(master) zeus start
Starting Zeus server v0.15.3
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus test (alias: rspec, testrb) [run to see backtrace]
```

Also I put up a test repo to reproduce: https://github.com/mehulkar/test_zeus

**Comment by qnm** [comment]
@mehulkar Please take a look at https://github.com/mehulkar/test_zeus/pull/1

**Comment by qnm** [comment]
@e2 The 'fix' for this particular issue is updating rspecs `spec_helper` template with a require - I wonder if it's worth asking them if we can change it to include it? Surely it's good practice to require anyway?

**Comment by mehulkar** [comment]
@qnm thanks so much for that PR with the fix. I'm wondering if this "fix" is something that we can accomplish in the out of box setup? I start new projects maybe once every few months and usability-wise, it would be really nice to have things just work™.

**Comment by qnm** [comment]
@mehulkar That file comes from `rspec --init` and is a template in `rspec-core` iirc. I'll chat with @e2 and see if he thinks it should be included by rspec, or if there's something else we can do.

**Comment by e2** [comment]
I'm confused here - spec_helper does not need to include rspec files. Are the specs being run with the rspec command? Or are they being run by plain ruby? (which is wrong).

Also, rails projects are supposed to include rails_helper, not spec_helper (for faster startup time).  the default rspec template is probably not for rails projects.

Sorry if I'm missing something easy to check - I don't have access to a dev workstation to check right now.

**Comment by mehulkar** [comment]
> Are the specs being run with the rspec command? 

they're being run by whatever guard-zeus does by default (the Guardfile generated by `guard zeus init`

> Also, rails projects are supposed to include rails_helper

default `rspec-rails` gives you `rails_helper` _and_ `spec_helper`. The latter being for specs that don't need the whole Rails environment. requiring 'spec_helper` anywhere throws the error above

**Comment by e2** [comment]
@qnm - I get it now ... Zeus is including the 'spec/spec_helper' file manually here: 

https://github.com/burke/zeus/blob/v0.15.4/rubygem/lib/zeus/rails.rb#L199

I don't think this is a good practice (including spec_helper from ruby and expecting it to work).

I get that zeus forks, etc. and that avoiding overhead is important ... but I'm not sure RSpec supports something like this. 

Ideally, if spec_helper is detected, the spec file should be run with the `rspec` command manually (which allows full RSpec runner configuration, etc.). RSpec should require the files it needs from the `.rspec` and `.rspec-local` files. I don't think Zeus should load spec_helper manually unless it's an essential hack to get forking working properly.

Or, at least Zeus should preload RSpec itself (`require 'rspec/core'`).

(Sorry, I don't time to wrap my head around again how the prefork works as related to the plans).

Perhaps this is a Zeus issue (in the rails.rb plan)?

**Comment by mehulkar** [comment]
@e2 that line you linked to, right above it the comment says that the intention if for Rspec < 3.0. The way it determines that is by the existence of the `spec_helper` file. In this case, `spec_helper.rb` exists but it is _not_ Rspec < 3.0. Maybe `zeus` should determine Rspec  < 3.0 some other way?

**Comment by e2** [comment]
@mehulkar - think the comments are just wrong or outdated. rails_helper will normally include spec_helper if necessary, and '.rspec' should define which is used, so it's more about Rails vs non-Rails projects. I think has supported both the `--require` option and `.rspec` files for a very long time, so there's no check really needed here.

@qnm - the runner is an essential part of RSpec - that's why it doesn't make sense to "require a file" even though that's sufficient for minitest/testrb. I'm not sure how to properly set things up without the runner though - so I don't know if requiring 'rspec/core' is sufficient at all.

**Comment by qnm** [comment]
@mehulkar I think the fix for this issue is outside the scope of `guard-zeus`. I think I'll close this issue, please let me know if you disagree.
